from __future__ import annotations

import json
import mimetypes
import time
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from src.baluffo_config import get_security_defaults
from src.bridge.performance_profile import record_operation_duration
from src.jobs.common.config import LIGHTWEIGHT_OUTPUT_FIELDS
from src.pipeline_io import serialize_rows_for_json, write_atomic_if_changed
from src.shared.json_io import PIPELINE_GZIP_JSON_NAMES
from src.storage_metrics import duration_ms, record_storage_read

API_PREFIXES = (
    "/desktop-local-data",
    "/app",
    "/registry",
    "/sources",
    "/discovery",
    "/tasks",
    "/fetcher",
    "/ops",
    "/sync",
    "/source-policy",
    "/dedup",
)

ROOT_DATA_FILE_ALIASES = frozenset(
    {
        "jobs-fetch-report.json",
        "jobs-lifecycle-state.json",
        "jobs-source-state.json",
        "jobs-unified-startup.json",
        "jobs-unified-light.json",
        "jobs-unified.json",
        "jobs-unified.csv",
        "source-discovery-candidates.json",
        "source-discovery-config.json",
        "source-discovery-report.json",
        "source-registry-active.json",
        "source-registry-pending.json",
        "source-registry-rejected.json",
        "source-registry-tombstones.json",
    }
)

STATIC_CACHE_CONTROL = "public, max-age=3600"
CONTAINER_ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable"
NO_STORE_CACHE_CONTROL = "no-store, no-cache, must-revalidate, max-age=0"

_ROOT_STATIC_FILES = frozenset(
    {
        "admin.html",
        "favicon.ico",
        "index.html",
        "jobs.html",
        "saved.html",
        "theme.js",
    }
)
_PAGE_ALIASES = {
    "admin": "admin.html",
    "jobs": "jobs.html",
    "saved": "saved.html",
}
_CONTAINER_PAGE_FILES = frozenset({"admin.html", "jobs.html", "saved.html"})
_CONTAINER_ASSET_PREFIX = "container-assets"
_STATIC_DIRECTORIES = frozenset({"frontend", "probes", "styles"})
_PACKAGING_STATIC_FILES = frozenset({"packaging/baluffo.png"})
_STATIC_DATA_DIRECTORIES = frozenset({"contracts", "defaults"})
_ROOT_DATA_READ_SURFACES = {
    "jobs-unified-light.json": "jobsFeed.staticLight",
    "jobs-unified-startup.json": "jobsFeed.staticStartup",
    "jobs-unified.json": "jobsFeed.staticFull",
    "jobs-fetch-report.json": "fetchReport.static",
}
STARTUP_FEED_BACKFILL_LIMIT = 10


def is_api_path(path: str) -> bool:
    route_path = str(path or "").strip() or "/"
    return any(
        route_path == prefix or route_path.startswith(f"{prefix}/") for prefix in API_PREFIXES
    )


def render_container_runtime_config_js() -> str:
    security_defaults = get_security_defaults()
    payload = {
        "bridge": {
            "sameOrigin": True,
        },
        "security": {
            "github_app_enabled_default": bool(security_defaults["github_app_enabled_default"]),
        },
        "runtime": {
            "mode": "container",
            "localDataMode": "bridge",
        },
    }
    rendered = json.dumps(payload, indent=2, ensure_ascii=True)
    return (
        "// Generated by src.container_server for container deployments.\n"
        "// Contains only frontend-safe runtime defaults.\n"
        f"globalThis.BALUFFO_FRONTEND_RUNTIME_CONFIG = Object.freeze({rendered});\n"
    )


def _safe_posix_parts(path: str) -> list[str]:
    return [part for part in PurePosixPath(path).parts if part not in {"", ".", ".."}]


def _existing_path_under(base_dir: Path, rel_parts: list[str]) -> Path | None:
    base = Path(base_dir).resolve()
    candidate = base.joinpath(*rel_parts).resolve()
    try:
        candidate.relative_to(base)
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def _allowed_data_parts(parts: list[str]) -> list[str]:
    if not parts:
        return []
    requested_name = parts[-1]
    requested_base = requested_name.removesuffix(".gz")
    if len(parts) == 1 and requested_base in ROOT_DATA_FILE_ALIASES:
        return parts
    if parts[0] in _STATIC_DATA_DIRECTORIES and requested_base.endswith(".json"):
        return parts
    return []


def _cache_control_for_path(normalized: str) -> str:
    suffix = Path(normalized).suffix.lower()
    if normalized == "frontend-runtime-config.js":
        return NO_STORE_CACHE_CONTROL
    if normalized.startswith("data/") or normalized in ROOT_DATA_FILE_ALIASES:
        return NO_STORE_CACHE_CONTROL
    if suffix in {".html", ""}:
        return NO_STORE_CACHE_CONTROL
    return STATIC_CACHE_CONTROL


def _content_type_for_path(path: Path, *, gzip_json: bool = False) -> str:
    if gzip_json:
        return "application/json; charset=utf-8"
    if path.name.endswith(".js"):
        return "application/javascript; charset=utf-8"
    if path.suffix.lower() == ".css":
        return "text/css; charset=utf-8"
    if path.suffix.lower() == ".html":
        return "text/html; charset=utf-8"
    if path.suffix.lower() == ".json":
        return "application/json; charset=utf-8"
    content_type, _encoding = mimetypes.guess_type(str(path))
    return content_type or "application/octet-stream"


def _accepts_gzip(handler: Any) -> bool:
    header = ""
    try:
        header = str(handler.headers.get("Accept-Encoding", ""))
    except Exception:
        header = ""
    return any(part.strip().lower() == "gzip" for part in header.split(","))


def _rows_from_jobs_payload(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        rows = payload
    elif isinstance(payload, dict) and isinstance(payload.get("jobs"), list):
        rows = payload["jobs"]
    else:
        return []
    return [dict(row) for row in rows if isinstance(row, dict)]


def _load_jobs_rows(path: Path) -> list[dict[str, Any]]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    return _rows_from_jobs_payload(payload)


@dataclass(frozen=True)
class StaticFileService:
    static_root: Path
    data_dir: Path

    def _resolve_data_path(self, normalized: str) -> tuple[Path | None, bool]:
        if normalized in ROOT_DATA_FILE_ALIASES:
            safe_parts = [normalized]
        elif normalized.startswith("data/"):
            safe_parts = _allowed_data_parts(_safe_posix_parts(normalized[5:]))
        else:
            return None, False
        if not safe_parts:
            return None, False
        requested_name = safe_parts[-1]
        if requested_name.removesuffix(".gz") in PIPELINE_GZIP_JSON_NAMES:
            candidates = []
            if requested_name.endswith(".gz"):
                candidates.append(safe_parts)
                candidates.append([*safe_parts[:-1], requested_name.removesuffix(".gz")])
            else:
                candidates.append([*safe_parts[:-1], f"{requested_name}.gz"])
                candidates.append(safe_parts)
        else:
            candidates = [safe_parts]
        for base_dir in (self.data_dir, self.static_root / "data"):
            for rel_parts in candidates:
                candidate = _existing_path_under(Path(base_dir), rel_parts)
                if candidate is not None:
                    return candidate, candidate.suffix == ".gz"
        return self._resolve_missing_data_path(safe_parts)

    def _resolve_missing_data_path(self, safe_parts: list[str]) -> tuple[Path | None, bool]:
        if safe_parts == ["jobs-unified-startup.json"]:
            backfilled = self._backfill_startup_feed()
            if backfilled is not None:
                return backfilled, False
        return None, False

    def _backfill_startup_feed(self) -> Path | None:
        startup_path = self.data_dir / "jobs-unified-startup.json"
        if startup_path.is_file():
            return startup_path
        light_candidates = (
            self.data_dir / "jobs-unified-light.json",
            self.static_root / "data" / "jobs-unified-light.json",
        )
        for light_path in light_candidates:
            if not light_path.is_file():
                continue
            rows = _load_jobs_rows(light_path)
            if not rows:
                continue
            startup_rows = rows[:STARTUP_FEED_BACKFILL_LIMIT]
            try:
                startup_path.parent.mkdir(parents=True, exist_ok=True)
                if startup_path.is_file():
                    return startup_path
                write_atomic_if_changed(
                    startup_path,
                    serialize_rows_for_json(startup_rows, LIGHTWEIGHT_OUTPUT_FIELDS),
                )
            except OSError:
                return None
            return startup_path if startup_path.is_file() else None
        return None

    def _normalize_static_path(self, path: str) -> str:
        normalized = str(path or "").split("?", 1)[0].split("#", 1)[0].lstrip("/")
        if normalized in {"", "/"}:
            return "index.html"
        if normalized in _PAGE_ALIASES:
            return _PAGE_ALIASES[normalized]
        return normalized

    def _resolve_static_path(self, normalized: str) -> Path | None:
        safe_parts = _safe_posix_parts(normalized)
        if not safe_parts:
            return None
        safe_normalized = "/".join(safe_parts)
        top_level = safe_parts[0]
        if safe_normalized in _ROOT_STATIC_FILES or safe_normalized in _PACKAGING_STATIC_FILES:
            return _existing_path_under(self.static_root, safe_parts)
        if top_level in _STATIC_DIRECTORIES:
            return _existing_path_under(self.static_root, safe_parts)
        if "." not in safe_parts[-1]:
            return _existing_path_under(self.static_root, ["index.html"])
        return None

    def _container_frontend_root(self) -> Path:
        return self.static_root / ".container-frontend"

    def _resolve_container_path(self, normalized: str) -> tuple[Path | None, bool]:
        container_root = self._container_frontend_root()
        if not container_root.is_dir():
            return None, False
        if normalized in _CONTAINER_PAGE_FILES:
            return _existing_path_under(container_root, [normalized]), False
        if not normalized.startswith(f"{_CONTAINER_ASSET_PREFIX}/"):
            return None, False
        safe_parts = _safe_posix_parts(normalized)
        if len(safe_parts) < 2 or safe_parts[0] != _CONTAINER_ASSET_PREFIX:
            return None, False
        return _existing_path_under(container_root, safe_parts[1:]), True

    def handle_get(self, handler: Any, *, path: str) -> bool:
        if is_api_path(path):
            return False
        normalized = self._normalize_static_path(path)
        if normalized == "frontend-runtime-config.js":
            body = render_container_runtime_config_js().encode("utf-8")
            handler.send_bytes(
                body,
                content_type="application/javascript; charset=utf-8",
                status=200,
                cache_control=NO_STORE_CACHE_CONTROL,
            )
            return True

        container_path, is_container_asset = self._resolve_container_path(normalized)
        if container_path is not None:
            read_path = container_path
            content_encoding = ""
            if is_container_asset and _accepts_gzip(handler):
                gzip_path = Path(f"{container_path}.gz")
                if gzip_path.is_file():
                    read_path = gzip_path
                    content_encoding = "gzip"
            handler.send_bytes(
                read_path.read_bytes(),
                content_type=_content_type_for_path(container_path),
                status=200,
                cache_control=CONTAINER_ASSET_CACHE_CONTROL
                if is_container_asset
                else NO_STORE_CACHE_CONTROL,
                content_encoding=content_encoding,
            )
            return True

        data_path, gzip_json = self._resolve_data_path(normalized)
        candidate = data_path or self._resolve_static_path(normalized)
        if candidate is None:
            handler.send_json({"error": "Not found"}, status=404)
            return True

        started_at = time.perf_counter()
        failed = False
        body = b""
        try:
            body = candidate.read_bytes()
        except OSError:
            failed = True
            raise
        finally:
            if data_path is not None:
                artifact = normalized.removeprefix("data/")
                artifact = artifact.removesuffix(".gz")
                surface = _ROOT_DATA_READ_SURFACES.get(artifact, "runtimeData.static")
                elapsed_ms = duration_ms(started_at)
                record_storage_read(
                    surface=surface,
                    artifact=artifact,
                    storage_kind="file.gz" if gzip_json else "file",
                    duration_ms=elapsed_ms,
                    bytes_read=len(body),
                    row_count=0,
                    failed=failed,
                    data_dir=self.data_dir,
                )
                record_operation_duration(f"storage.read.{surface}", elapsed_ms, error=failed)
        handler.send_bytes(
            body,
            content_type=_content_type_for_path(candidate, gzip_json=gzip_json),
            status=200,
            cache_control=_cache_control_for_path(normalized),
            content_encoding="gzip" if gzip_json else "",
        )
        return True
