from __future__ import annotations

import json
import mimetypes
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from src.baluffo_config import get_security_defaults
from src.shared.json_io import PIPELINE_GZIP_JSON_NAMES

API_PREFIXES = (
    "/desktop-local-data",
    "/app",
    "/registry",
    "/sources",
    "/discovery",
    "/tasks",
    "/fetcher",
    "/ops",
    "/sync",
    "/source-policy",
    "/dedup",
)

ROOT_DATA_FILE_ALIASES = frozenset(
    {
        "jobs-fetch-report.json",
        "jobs-lifecycle-state.json",
        "jobs-source-state.json",
        "jobs-unified-startup.json",
        "jobs-unified-light.json",
        "jobs-unified.json",
        "jobs-unified.csv",
        "source-discovery-candidates.json",
        "source-discovery-config.json",
        "source-discovery-report.json",
        "source-registry-active.json",
        "source-registry-pending.json",
        "source-registry-rejected.json",
        "source-registry-tombstones.json",
    }
)

STATIC_CACHE_CONTROL = "public, max-age=3600"
NO_STORE_CACHE_CONTROL = "no-store, no-cache, must-revalidate, max-age=0"

_ROOT_STATIC_FILES = frozenset(
    {
        "admin.html",
        "favicon.ico",
        "index.html",
        "jobs.html",
        "saved.html",
        "theme.js",
    }
)
_PAGE_ALIASES = {
    "admin": "admin.html",
    "jobs": "jobs.html",
    "saved": "saved.html",
}
_STATIC_DIRECTORIES = frozenset({"frontend", "probes", "styles"})
_PACKAGING_STATIC_FILES = frozenset({"packaging/baluffo.png"})
_STATIC_DATA_DIRECTORIES = frozenset({"contracts", "defaults"})


def is_api_path(path: str) -> bool:
    route_path = str(path or "").strip() or "/"
    return any(
        route_path == prefix or route_path.startswith(f"{prefix}/") for prefix in API_PREFIXES
    )


def render_container_runtime_config_js() -> str:
    security_defaults = get_security_defaults()
    payload = {
        "bridge": {
            "sameOrigin": True,
        },
        "security": {
            "github_app_enabled_default": bool(security_defaults["github_app_enabled_default"]),
        },
        "runtime": {
            "mode": "container",
            "localDataMode": "bridge",
        },
    }
    rendered = json.dumps(payload, indent=2, ensure_ascii=True)
    return (
        "// Generated by src.container_server for container deployments.\n"
        "// Contains only frontend-safe runtime defaults.\n"
        f"globalThis.BALUFFO_FRONTEND_RUNTIME_CONFIG = Object.freeze({rendered});\n"
    )


def _safe_posix_parts(path: str) -> list[str]:
    return [part for part in PurePosixPath(path).parts if part not in {"", ".", ".."}]


def _existing_path_under(base_dir: Path, rel_parts: list[str]) -> Path | None:
    base = Path(base_dir).resolve()
    candidate = base.joinpath(*rel_parts).resolve()
    try:
        candidate.relative_to(base)
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def _allowed_data_parts(parts: list[str]) -> list[str]:
    if not parts:
        return []
    requested_name = parts[-1]
    requested_base = requested_name.removesuffix(".gz")
    if len(parts) == 1 and requested_base in ROOT_DATA_FILE_ALIASES:
        return parts
    if parts[0] in _STATIC_DATA_DIRECTORIES and requested_base.endswith(".json"):
        return parts
    return []


def _cache_control_for_path(normalized: str) -> str:
    suffix = Path(normalized).suffix.lower()
    if normalized == "frontend-runtime-config.js":
        return NO_STORE_CACHE_CONTROL
    if normalized.startswith("data/") or normalized in ROOT_DATA_FILE_ALIASES:
        return NO_STORE_CACHE_CONTROL
    if suffix in {".html", ""}:
        return NO_STORE_CACHE_CONTROL
    return STATIC_CACHE_CONTROL


def _content_type_for_path(path: Path, *, gzip_json: bool = False) -> str:
    if gzip_json:
        return "application/json; charset=utf-8"
    if path.name.endswith(".js"):
        return "application/javascript; charset=utf-8"
    if path.suffix.lower() == ".css":
        return "text/css; charset=utf-8"
    if path.suffix.lower() == ".html":
        return "text/html; charset=utf-8"
    if path.suffix.lower() == ".json":
        return "application/json; charset=utf-8"
    content_type, _encoding = mimetypes.guess_type(str(path))
    return content_type or "application/octet-stream"


@dataclass(frozen=True)
class StaticFileService:
    static_root: Path
    data_dir: Path

    def _resolve_data_path(self, normalized: str) -> tuple[Path | None, bool]:
        if normalized in ROOT_DATA_FILE_ALIASES:
            safe_parts = [normalized]
        elif normalized.startswith("data/"):
            safe_parts = _allowed_data_parts(_safe_posix_parts(normalized[5:]))
        else:
            return None, False
        if not safe_parts:
            return None, False
        requested_name = safe_parts[-1]
        if requested_name.removesuffix(".gz") in PIPELINE_GZIP_JSON_NAMES:
            candidates = []
            if requested_name.endswith(".gz"):
                candidates.append(safe_parts)
                candidates.append([*safe_parts[:-1], requested_name.removesuffix(".gz")])
            else:
                candidates.append([*safe_parts[:-1], f"{requested_name}.gz"])
                candidates.append(safe_parts)
        else:
            candidates = [safe_parts]
        for base_dir in (self.data_dir, self.static_root / "data"):
            for rel_parts in candidates:
                candidate = _existing_path_under(Path(base_dir), rel_parts)
                if candidate is not None:
                    return candidate, candidate.suffix == ".gz"
        return None, False

    def _normalize_static_path(self, path: str) -> str:
        normalized = str(path or "").split("?", 1)[0].split("#", 1)[0].lstrip("/")
        if normalized in {"", "/"}:
            return "index.html"
        if normalized in _PAGE_ALIASES:
            return _PAGE_ALIASES[normalized]
        return normalized

    def _resolve_static_path(self, normalized: str) -> Path | None:
        safe_parts = _safe_posix_parts(normalized)
        if not safe_parts:
            return None
        safe_normalized = "/".join(safe_parts)
        top_level = safe_parts[0]
        if safe_normalized in _ROOT_STATIC_FILES or safe_normalized in _PACKAGING_STATIC_FILES:
            return _existing_path_under(self.static_root, safe_parts)
        if top_level in _STATIC_DIRECTORIES:
            return _existing_path_under(self.static_root, safe_parts)
        if "." not in safe_parts[-1]:
            return _existing_path_under(self.static_root, ["index.html"])
        return None

    def handle_get(self, handler: Any, *, path: str) -> bool:
        if is_api_path(path):
            return False
        normalized = self._normalize_static_path(path)
        if normalized == "frontend-runtime-config.js":
            body = render_container_runtime_config_js().encode("utf-8")
            handler.send_bytes(
                body,
                content_type="application/javascript; charset=utf-8",
                status=200,
                cache_control=NO_STORE_CACHE_CONTROL,
            )
            return True

        data_path, gzip_json = self._resolve_data_path(normalized)
        candidate = data_path or self._resolve_static_path(normalized)
        if candidate is None:
            handler.send_json({"error": "Not found"}, status=404)
            return True

        body = candidate.read_bytes()
        handler.send_bytes(
            body,
            content_type=_content_type_for_path(candidate, gzip_json=gzip_json),
            status=200,
            cache_control=_cache_control_for_path(normalized),
            content_encoding="gzip" if gzip_json else "",
        )
        return True
