import js from "@eslint/js";

export default [
  {
    ignores: [
      "node_modules/**",
      "data/**",
      "docs/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },

  js.configs.recommended,

  {
    files: [
      "frontend/**/*.js",
      "tests/**/*.js",
      "tests/**/*.mjs",
      "scripts/**/*.mjs",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        navigator: "readonly",
        HTMLInputElement: "readonly",
        performance: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        alert: "readonly",
        location: "readonly",
        history: "readonly",
        requestAnimationFrame: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLTextAreaElement: "readonly",
        process: "readonly",
        AbortController: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        IDBKeyRange: "readonly",
        atob: "readonly",
        btoa: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-console": "off",
    },
  },

  {
    files: ["tests/**/*.js", "tests/**/*.mjs"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        before: "readonly",
        beforeEach: "readonly",
        after: "readonly",
        afterEach: "readonly",
        global: "readonly",
        Blob: "readonly",
      },
    },
    rules: {
      "no-unused-expressions": "off",
    },
  },

  // Root-level JS files (browser scripts)
  {
    files: ["theme.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        _: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
    },
  },

  // Root-level ES module files
  {
    files: [
      "admin-config.js",
      "app-local-data-client.js",
      "desktop-local-data-client.js",
      "eslint.config.js",
      "frontend-runtime-config.js",
      "jobs-parsing-utils.js",
      "jobs-state.js",
      "local-data-client.js",
      "playwright.config.js",
      "saved-zip-utils.js",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        navigator: "readonly",
        history: "readonly",
        location: "readonly",
        _: "readonly",
        alert: "readonly",
        process: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        AbortController: "readonly",
        atob: "readonly",
        btoa: "readonly",
        IDBKeyRange: "readonly",
        indexedDB: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
    },
  },
];