[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
follow_imports = silent
strict_optional = True
warn_unused_ignores = True
files = src, tests
