import { UI_TOKENS, ui } from "../../shared/ui/selectors.js";

export function cacheJobsDom(doc = document) {
  const t = UI_TOKENS.jobs;
  const g = UI_TOKENS.global;

  return {
    jobsList: doc.querySelector(ui(t.list)),
    workTypeFilter: doc.querySelector(ui(t.workTypeFilter)),
    lifecycleStatusFilter: doc.querySelector(ui(t.lifecycleStatusFilter)),
    countryFilter: doc.querySelector(ui(t.countryFilter)),
    countryPickerBtn: doc.querySelector(ui(t.countryPickerBtn)),
    countryPickerPanel: doc.querySelector(ui(t.countryPickerPanel)),
    countryPickerSearch: doc.querySelector(ui(t.countryPickerSearch)),
    countryPickerOptions: doc.querySelector(ui(t.countryPickerOptions)),
    countryPickerClearBtn: doc.querySelector(ui(t.countryPickerClearBtn)),
    cityFilter: doc.querySelector(ui(t.cityFilter)),
    sectorFilter: doc.querySelector(ui(t.sectorFilter)),
    professionFilter: doc.querySelector(ui(t.professionFilter)),
    professionSearchFilter: doc.querySelector(ui(t.professionSearchFilter)),
    searchFilter: doc.querySelector(ui(t.searchFilter)),
    sortFilter: doc.querySelector(ui(t.sortFilter)),
    resultsSummary: doc.querySelector(ui(t.resultsSummary)),
    countrySelectionBadge: doc.querySelector(ui(t.countrySelectionBadge)),
    sourceStatus: doc.querySelector(ui(t.sourceStatus)),
    fetchProgress: doc.querySelector(ui(t.fetchProgress)),
    guestNoticeEl: doc.querySelector(ui(t.guestNotice)),
    pagination: doc.querySelector(ui(t.pagination)),
    refreshJobsBtn: doc.querySelector(ui(t.refreshJobsBtn)),
    desktopUpdateToggleBtn: doc.querySelector(ui(t.desktopUpdateToggleBtn)),
    desktopUpdatePanel: doc.querySelector(ui(t.desktopUpdatePanel)),
    desktopUpdateTitle: doc.querySelector(ui(t.desktopUpdateTitle)),
    desktopUpdateBody: doc.querySelector(ui(t.desktopUpdateBody)),
    desktopUpdateMeta: doc.querySelector(ui(t.desktopUpdateMeta)),
    desktopUpdateProgress: doc.querySelector(ui(t.desktopUpdateProgress)),
    desktopUpdatePrimaryBtn: doc.querySelector(ui(t.desktopUpdatePrimaryBtn)),
    desktopUpdateSecondaryBtn: doc.querySelector(ui(t.desktopUpdateSecondaryBtn)),
    desktopUpdateReleaseNotes: doc.querySelector(ui(t.desktopUpdateReleaseNotes)),
    refreshJobsNeededBadgeEl: doc.querySelector(ui(t.refreshJobsNeededBadge)),
    jobsLastUpdatedEl: doc.querySelector(ui(t.jobsLastUpdated)),
    authStatus: doc.querySelector(ui(g.authStatus)),
    authStatusHint: doc.querySelector(ui(g.authStatusHint)),
    authAvatar: doc.querySelector(ui(g.authAvatar)),
    authSignInBtn: doc.querySelector(ui(g.authSignInBtn)),
    authSignOutBtn: doc.querySelector(ui(g.authSignOutBtn)),
    adminPageBtn: doc.querySelector(ui(g.adminPageBtn)),
    savedJobsBtn: doc.querySelector(ui(g.savedPageBtn)),
    activeFiltersSummaryEl: doc.querySelector(ui(t.activeFiltersSummary)),
    quickActionsEl: doc.querySelector(ui(t.quickActions)),
    customizeQuickFiltersBtn: doc.querySelector(ui(t.customizeQuickFiltersBtn)),
    quickFiltersPanel: doc.querySelector(ui(t.quickFiltersPanel)),
    quickFiltersOptionsEl: doc.querySelector(ui(t.quickFiltersOptions)),
    quickFiltersResetBtn: doc.querySelector(ui(t.quickFiltersResetBtn)),
    dataSourcesListEl: doc.querySelector(ui(t.dataSourcesList)),
    dataSourcesCaptionEl: doc.querySelector(ui(t.dataSourcesCaption)),
    dataSourcesDetailsEl: doc.querySelector(ui(t.dataSourcesList))?.closest?.("details") || null,
    jobsPipelineRunBtn: doc.querySelector(ui(t.jobsPipelineRunBtn))
  };
}
