import pytest

from src import jobs_fetcher as jf


@pytest.mark.parametrize(
    "value, expected_country",
    [
        ("(none) Vancouver", ""),
        ("Apr. 06", ""),
        ("Art Team Lead", ""),
        ("As a Product Associate", ""),
        ("Any", ""),
        ("Apps for kids", ""),
        ("BLANK", ""),
        ("CA - Canada; US - United States", ""),
        ("CET +- 4", ""),
        ("CET +- 2", ""),
        ("COME FLY WITH US", ""),
        ("Chief Human Resource Officer (CHRO)", ""),
        ("Come work with us!", ""),
        ("Chronos: Before the Ashes", ""),
        ("Community", ""),
        ("Contact", ""),
        ("Create amazing characters that are efficient", ""),
        ("Create", ""),
        ("Cybersecurity", ""),
        ("Culture & Values", ""),
        ("Data & Engineering", ""),
        ("Data & Research", ""),
        ("Department", ""),
        ("Departments", ""),
        ("Do Not Sell My Information", ""),
        ("Do Not Share My Personal", ""),
        ("EU & NA", "EU & NA"),
        ("Endless Legend is a 4X turn", ""),
        ("Ensure brand message is consistent", ""),
        ("Entertain the world", ""),
        ("Filter by", ""),
        ("Filter roles by", ""),
        ("Filters", ""),
        ("Finance", ""),
        ("Finance & Accounting", ""),
        ("Find us on Facebook", ""),
        ("From Concept to Console: Meet Winslow", ""),
        ("Fully Remote", ""),
        ("Full", ""),
        ("Full-time", ""),
        ("Full or part", ""),
        ("Hybrid", ""),
        ("Games FQA Warsaw", ""),
        ("HUMANKIND is a turn", ""),
        ("Head of IP Licensing BD", ""),
        ("Head of Recruiting", ""),
        ("Help create video scripts", ""),
        ("In this role", ""),
        ("Imprint", ""),
        ("Internal Tools & Player Insights", ""),
        ("Interviews", ""),
        ("Junior", ""),
        ("Join our crew", ""),
        ("Join the community", ""),
        ("Join us", ""),
        ("Legal", ""),
        ("Ltd. )", ""),
        ("Mastery social platforms: Facebook", ""),
        ("Office", ""),
        ("On-site", ""),
        ("Organization", ""),
        ("People & Culture", ""),
        ("Senior Production Accountant (Feature) : 2026", ""),
        ("Sega of America", ""),
        ("Sign in", ""),
        ("Remote", ""),
        ("Spontaneous application", ""),
        ("Startup Directory Founder Directory Launch YC", ""),
        ("Student", ""),
        ("Student & Recent Graduates", ""),
        ("Studio", ""),
        ("Studios", ""),
        ("Titan Quest II Announced", ""),
        ("To be clear", ""),
        ("To be considered", ""),
        ("UNAVAILABLE", ""),
        ("UK", "UK"),
        ("Web Build Purple Imp", ""),
        ("Work & Innovation", ""),
        ("144 million+ Downloads", ""),
        ("3 to UTC+1", ""),
        ("9mo", ""),
        ("All", ""),
        ("Inc.", ""),
    ],
)
def test_canonicalize_job_with_reason_blanks_exact_city_noise_outliers(
    value: str,
    expected_country: str,
) -> None:
    row, reason = jf.canonicalize_job_with_reason(
        {
            "title": "Test Role",
            "company": "Test Studio",
            "city": value,
            "country": "Unknown",
            "jobLink": "https://example.com/test-role",
            "sector": "Tech",
        },
        source="static_source::static",
        fetched_at="2026-03-20T00:00:00Z",
    )
    assert reason == ""
    assert row is not None
    payload = row if isinstance(row, dict) else row.to_dict()
    assert payload["city"] == ""
    assert payload["country"] == expected_country
    assert payload["locationSummary"] == expected_country
    assert payload["locations"] == (
        [{"city": "", "country": expected_country}] if expected_country else []
    )
