import { UI_TOKENS, ui } from "../../shared/ui/selectors.js";

export function cacheSavedDom(doc = document) {
  const t = UI_TOKENS.saved;
  const g = UI_TOKENS.global;

  return {
    savedJobsListEl: doc.querySelector(ui(t.list)),
    savedSourceStatusEl: doc.querySelector(ui(t.sourceStatus)),
    savedAuthStatusEl: doc.querySelector(ui(t.authStatus)),
    savedAuthStatusHintEl: doc.querySelector(ui(t.authStatusHint)),
    savedAuthAvatarEl: doc.querySelector(ui(t.authAvatar)),
    signInBtnEl: doc.querySelector(ui(t.signInBtn)),
    signOutBtnEl: doc.querySelector(ui(t.signOutBtn)),
    jobsPageBtnEl: doc.querySelector(ui(g.jobsPageBtn)),
    adminPageBtnEl: doc.querySelector(ui(g.adminPageBtn)),
    addCustomJobBtnEl: doc.querySelector(ui(t.addCustomJobBtn)),
    customJobPanelEl: doc.querySelector(ui(t.customJobPanel)),
    customJobFormEl: doc.querySelector(ui(t.customJobForm)),
    customJobTitleEl: doc.querySelector(ui(t.customJobTitle)),
    customJobCompanyEl: doc.querySelector(ui(t.customJobCompany)),
    customJobCityEl: doc.querySelector(ui(t.customJobCity)),
    customJobCountryEl: doc.querySelector(ui(t.customJobCountry)),
    customJobWorkTypeEl: doc.querySelector(ui(t.customJobWorkType)),
    customJobContractTypeEl: doc.querySelector(ui(t.customJobContractType)),
    customJobSectorEl: doc.querySelector(ui(t.customJobSector)),
    customJobProfessionEl: doc.querySelector(ui(t.customJobProfession)),
    customJobLinkEl: doc.querySelector(ui(t.customJobLink)),
    customJobNotesEl: doc.querySelector(ui(t.customJobNotes)),
    customJobReminderEl: doc.querySelector(ui(t.customJobReminder)),
    customJobLinkWarningEl: doc.querySelector(ui(t.customJobLinkWarning)),
    customJobCancelBtnEl: doc.querySelector(ui(t.customJobCancelBtn)),
    customJobPanelTitleEl: doc.querySelector(ui(t.customJobPanelTitle)),
    customJobPanelHintEl: doc.querySelector(ui(t.customJobPanelHint)),
    customJobSaveBtnEl: doc.querySelector(ui(t.customJobSaveBtn)),
    savedCustomFilterBarEl: doc.querySelector(ui(t.customFilterBar)),
    savedCustomFilterCountEl: doc.querySelector(ui(t.customFilterCount)),
    savedCustomFilterBtnEls: Array.from(doc.querySelectorAll(ui(t.customFilterBtn))),
    savedSortBarEl: doc.querySelector(ui(t.sortBar)),
    savedSortBtnEls: Array.from(doc.querySelectorAll(ui(t.sortBtn))),
    savedGroupBarEl: doc.querySelector(ui(t.groupBar)),
    savedGroupBtnEls: Array.from(doc.querySelectorAll(ui(t.groupBtn))),
    savedReminderCounterEl: doc.querySelector(ui(t.reminderCounter)),
    historyPanelToggleBtnEl: doc.querySelector(ui(t.historyPanelToggleBtn)),
    savedWorkspaceStripEl: doc.querySelector(ui(t.workspaceStrip)),
    savedWorkspaceLayoutEl: doc.querySelector(ui(t.workspaceLayout)),
    savedMetricTotalEl: doc.querySelector(ui(t.metricTotal)),
    savedMetricRemindersEl: doc.querySelector(ui(t.metricReminders)),
    savedMetricActivityEl: doc.querySelector(ui(t.metricActivity)),
    exportBackupBtnEl: doc.querySelector(ui(t.exportBackupBtn)),
    exportIncludeFilesEl: doc.querySelector(ui(t.exportIncludeFiles)),
    importBackupBtnEl: doc.querySelector(ui(t.importBackupBtn)),
    importBackupInputEl: doc.querySelector(ui(t.importBackupInput)),
    activityPanelEl: doc.querySelector(ui(t.activityPanel)),
    activityPanelBodyEl: doc.querySelector(ui(t.activityPanelBody)),
    activityPanelStatusEl: doc.querySelector(ui(t.activityPanelStatus)),
    activityRefreshBtnEl: doc.querySelector(ui(t.activityRefreshBtn)),
    activityCloseBtnEl: doc.querySelector(ui(t.activityCloseBtn)),
    activityRecentBadgeEl: doc.querySelector(ui(t.activityRecentBadge)),
    activityScopeBtnEls: Array.from(doc.querySelectorAll(ui(t.activityScopeBtn))),
    activitySelectedJobEl: doc.querySelector(ui(t.activitySelectedJob))
  };
}
