from __future__ import annotations

from src.jobs.adapters.html_parsers import parse_jobpostings_from_html

from .static_detail_heuristics import (
    KNOWN_NON_JOB_DETAIL_HOSTS,
    KNOWN_NON_JOB_DETAIL_PATH_TOKENS,
    _detail_page_scan_start,
    _infer_detail_page_fields,
    _is_one_man_studio_noise_city,
    _source_tail_metrics,
    add_detail_link,
    choose_detail_traversal_mode,
    extract_rendered_card_jobs,
    is_known_non_job_detail_url,
    is_probable_job_detail_url,
    process_detail_html,
    process_detail_link,
    source_detail_concurrency_for,
    source_detail_limit_for,
    source_detail_retries_for,
)
from .static_runtime_support import (
    StaticHtmlFetcher,
    StaticHtmlFetchRequest,
    StaticSourceRuntimeConfig,
    build_static_entry_report,
    build_static_html_fetcher,
    build_static_source_deadline,
    build_static_source_runtime_config,
    effective_timeout_for_remaining_budget,
    remaining_static_source_budget_s,
    static_source_budget_exhausted,
    update_source_detail_taxonomy,
)

__all__ = [
    "KNOWN_NON_JOB_DETAIL_HOSTS",
    "KNOWN_NON_JOB_DETAIL_PATH_TOKENS",
    "StaticHtmlFetchRequest",
    "StaticHtmlFetcher",
    "StaticSourceRuntimeConfig",
    "_detail_page_scan_start",
    "_infer_detail_page_fields",
    "_is_one_man_studio_noise_city",
    "_source_tail_metrics",
    "add_detail_link",
    "build_static_entry_report",
    "build_static_html_fetcher",
    "build_static_source_deadline",
    "build_static_source_runtime_config",
    "choose_detail_traversal_mode",
    "effective_timeout_for_remaining_budget",
    "extract_rendered_card_jobs",
    "is_known_non_job_detail_url",
    "is_probable_job_detail_url",
    "process_detail_html",
    "process_detail_link",
    "parse_jobpostings_from_html",
    "remaining_static_source_budget_s",
    "source_detail_concurrency_for",
    "source_detail_limit_for",
    "source_detail_retries_for",
    "static_source_budget_exhausted",
    "update_source_detail_taxonomy",
]
