version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: deathuman-baluffo_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/deathuman/baluffo:0.2.108
    restart: on-failure
    init: true
    stop_grace_period: 1m
    environment:
      BALUFFO_CONTAINER_HOST: 0.0.0.0
      BALUFFO_CONTAINER_PORT: 8080
      BALUFFO_DATA_DIR: /data
      BALUFFO_BRIDGE_LOG_FORMAT: jsonl
    volumes:
      - ${APP_DATA_DIR}/data:/data
