import { UI_TOKENS, ui } from "../../shared/ui/selectors.js";

export function cacheAdminDom(doc = document) {
  const t = UI_TOKENS.admin;

  return {
    adminSourceStatusEl: doc.querySelector(ui(t.sourceStatus)),
    adminContentEl: doc.querySelector(ui(t.content)),
    adminRefreshBtnEl: doc.querySelector(ui(t.refreshBtn)),
    adminRunFetcherBtnEl: doc.querySelector(ui(t.runFetcherBtn)),
    adminRunFetcherIncrementalBtnEl: doc.querySelector(ui(t.runFetcherIncrementalBtn)),
    adminRunFetcherUncappedBtnEl: doc.querySelector(ui(t.runFetcherUncappedBtn)),
    adminRunFetcherForceBtnEl: doc.querySelector(ui(t.runFetcherForceBtn)),
    adminRefreshReportBtnEl: doc.querySelector(ui(t.refreshReportBtn)),
    adminClearLogBtnEl: doc.querySelector(ui(t.clearLogBtn)),
    adminClearDiscoveryLogBtnEl: doc.querySelector(ui(t.clearDiscoveryLogBtn)),
    adminRetryFailedBtnEl: doc.querySelector(ui(t.retryFailedBtn)),
    adminCopyFailuresBtnEl: doc.querySelector(ui(t.copyFailuresBtn)),
    adminTotalsEl: doc.querySelector(ui(t.totals)),
    adminUsersListEl: doc.querySelector(ui(t.usersList)),
    adminJobsBtnEl: doc.querySelector(ui(t.jobsPageBtn)),
    adminSavedBtnEl: doc.querySelector(ui(t.savedPageBtn)),
    adminFetcherLogEl: doc.querySelector(ui(t.fetcherLog)),
    adminFetcherProgressEl: doc.querySelector(ui(t.fetcherProgress)),
    adminFetcherProgressBarEl: doc.querySelector(ui(t.fetcherProgressBar)),
    adminFetcherProgressLabelEl: doc.querySelector(ui(t.fetcherProgressLabel)),
    adminRunDiscoveryBtnEl: doc.querySelector(ui(t.runDiscoveryBtn)),
    adminRunDiscoveryUncappedBtnEl: doc.querySelector(ui(t.runDiscoveryUncappedBtn)),
    adminLoadDiscoveryBtnEl: doc.querySelector(ui(t.loadDiscoveryBtn)),
    adminApproveSourcesBtnEl: doc.querySelector(ui(t.approveSourcesBtn)),
    adminRejectSourcesBtnEl: doc.querySelector(ui(t.rejectSourcesBtn)),
    adminDeleteSourcesBtnEl: doc.querySelector(ui(t.deleteSourcesBtn)),
    adminDiscoverySummaryEl: doc.querySelector(ui(t.discoverySummary)),
    adminManualSourceUrlEl: doc.querySelector(ui(t.manualSourceUrl)),
    adminAddManualSourceBtnEl: doc.querySelector(ui(t.addManualSourceBtn)),
    adminManualSourceFeedbackEl: doc.querySelector(ui(t.manualSourceFeedback)),
    adminPendingSourcesEl: doc.querySelector(ui(t.pendingSources)),
    adminActiveSourcesEl: doc.querySelector(ui(t.activeSources)),
    adminRejectedSourcesEl: doc.querySelector(ui(t.rejectedSources)),
    adminRestoreRejectedBtnEl: doc.querySelector(ui(t.restoreRejectedBtn)),
    adminDiscoveryLogEl: doc.querySelector(ui(t.discoveryLog)),
    adminDiscoveryProgressEl: doc.querySelector(ui(t.discoveryProgress)),
    adminDiscoveryProgressBarEl: doc.querySelector(ui(t.discoveryProgressBar)),
    adminDiscoveryProgressLabelEl: doc.querySelector(ui(t.discoveryProgressLabel)),
    adminDiscoveryLogDetailsEl: doc.querySelector(ui(t.discoveryLogDetails)),
    adminBridgeStatusBadgeEl: doc.querySelector(ui(t.bridgeStatusBadge)),
    adminShowZeroJobsToggleEl: doc.querySelector(ui(t.showZeroJobsToggle)),
    adminRefreshOpsBtnEl: doc.querySelector(ui(t.refreshOpsBtn)),
    adminSyncPullBtnEl: doc.querySelector(ui(t.syncPullBtn)),
    adminSyncPushBtnEl: doc.querySelector(ui(t.syncPushBtn)),
    adminSyncTestBtnEl: doc.querySelector(ui(t.syncTestBtn)),
    adminSyncStatusEl: doc.querySelector(ui(t.syncStatus)),
    adminSyncEnabledEl: doc.querySelector(ui(t.syncEnabled)),
    adminSyncConfigHintEl: doc.querySelector(ui(t.syncConfigHint)),
    adminOpsAlertsEl: doc.querySelector(ui(t.opsAlerts)),
    adminOpsKpisEl: doc.querySelector(ui(t.opsKpis)),
    adminOpsScheduleEl: doc.querySelector(ui(t.opsSchedule)),
    adminOpsFetcherMetricsEl: doc.querySelector(ui(t.opsFetcherMetrics)),
    adminOpsTrendsEl: doc.querySelector(ui(t.opsTrends)),
    adminOpsHistoryEl: doc.querySelector(ui(t.opsHistory)),
    adminFetcherProgressBadgeEl: doc.querySelector(ui(t.fetcherProgressBadge)),
    adminDiscoveryProgressBadgeEl: doc.querySelector(ui(t.discoveryProgressBadge)),
    adminOpsProgressBadgeEl: doc.querySelector(ui(t.opsProgressBadge)),
    adminSourceFilterBtnEls: Array.from(doc.querySelectorAll(ui(t.sourceFilterBtn)))
  };
}
