#!/usr/bin/env python3
"""Generate the frontend-safe runtime config module."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = ROOT / "frontend-runtime-config.js"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.baluffo_config import get_bridge_defaults, get_security_defaults
from scripts.python_version_guard import ensure_required_python


def build_frontend_runtime_config_payload() -> Dict[str, Dict[str, Any]]:
    bridge_defaults = get_bridge_defaults()
    security_defaults = get_security_defaults()
    return {
        "bridge": {
            "host": str(bridge_defaults["host"]),
            "port": int(bridge_defaults["port"]),
        },
        "security": {
            "admin_pin_default": str(security_defaults["admin_pin_default"]),
            "github_app_enabled_default": bool(security_defaults["github_app_enabled_default"]),
        },
    }


def render_frontend_runtime_config_js(payload: Dict[str, Dict[str, Any]]) -> str:
    rendered = json.dumps(payload, indent=2, ensure_ascii=True)
    return (
        "// Generated by scripts/build_frontend_runtime_config.py.\n"
        "// Contains only frontend-safe runtime defaults.\n"
        "// Do not hand-edit; regenerate from baluffo.config.json.\n"
        f"export const BALUFFO_FRONTEND_RUNTIME_CONFIG = Object.freeze({rendered});\n"
    )


def write_frontend_runtime_config(output_path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_frontend_runtime_config_js(build_frontend_runtime_config_payload()),
        encoding="utf-8",
    )
    return output_path


def main() -> int:
    ensure_required_python()
    write_frontend_runtime_config()
    print(str(DEFAULT_OUTPUT_PATH))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
