import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
export const unitTestDir = path.join(repoRoot, "tests", "frontend", "unit");
export const manifestPath = path.join(unitTestDir, "all.test.mjs");
const manifestName = path.basename(manifestPath);

export async function listUnitTestFiles() {
  const entries = await readdir(unitTestDir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => name.endsWith(".test.mjs") && name !== manifestName)
    .sort((left, right) => left.localeCompare(right));
}

export function buildManifestContent(testFiles) {
  const imports = testFiles.map((name) => `import "./${name}";`).join("\n");
  return [
    "// Auto-generated by scripts/sync_frontend_unit_manifest.mjs.",
    "// Do not hand-edit this file; run `npm run sync:test-manifest` instead.",
    imports,
    "",
  ].join("\n");
}

export async function syncFrontendUnitManifest({ check = false } = {}) {
  const testFiles = await listUnitTestFiles();
  const expectedContent = buildManifestContent(testFiles);
  const currentContent = await readFile(manifestPath, "utf8").catch((error) => {
    if (error.code === "ENOENT") {
      return "";
    }
    throw error;
  });

  if (currentContent === expectedContent) {
    return { changed: false, testFiles };
  }

  if (check) {
    throw new Error(
      "Frontend unit manifest is stale. Run `npm run sync:test-manifest` to regenerate tests/frontend/unit/all.test.mjs.",
    );
  }

  await writeFile(manifestPath, expectedContent, "utf8");
  return { changed: true, testFiles };
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectRun) {
  const check = process.argv.includes("--check");
  try {
    const result = await syncFrontendUnitManifest({ check });
    if (check) {
      console.log(
        `Frontend unit manifest is current (${result.testFiles.length} discovered test files).`,
      );
    } else if (result.changed) {
      console.log(
        `Regenerated tests/frontend/unit/all.test.mjs with ${result.testFiles.length} discovered test files.`,
      );
    } else {
      console.log(
        `Frontend unit manifest already current (${result.testFiles.length} discovered test files).`,
      );
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
